### ISSUE TITLE
Dragons can walk right through glass

### ISSUE THREAD

**Issue by M3RGeo** [backuporg/dragon-mounts#1]
Dragons can walk right through glass, I'm Unsure if they can walk through any other blocks, or if this is just a problem with the forest dragons.
![2021-03-24_20 59 11](https://user-images.githubusercontent.com/52404756/112368813-28362000-8ce4-11eb-9fb9-2d5b95d8bb36.png)

**Comment by Sunconure11** [comment]
Try testing with blocks like iron bars, fences, etc. Although keep in mind this build is not gonna get much support.

**Comment by Sunconure11** [comment]
Mod is no longer supported
