### ISSUE TITLE
Dragon's head looks straight up while flying

### ISSUE THREAD

**Issue by Nafen-F** [backuporg/dragon-mounts#2]
There was a small issue with the new version that was uploaded earlier today. When the player is flying on the dragon, the dragon's head looks up an unnatural angle. Nothing game breaking, but worth looking into a quick fix.

**Comment by Sunconure11** [comment]
Fixed in dev. Expect a new build soon.

**Comment by Nafen-F** [comment]
awesome! thanks for the quick response
