### ISSUE TITLE
Give Dragons other uses besides flight.

### ISSUE THREAD

**Issue by MagmaSlime123** [backuporg/dragon-mounts#3]
Title. Like the normal dragon, they could shoot dragon fireballs and create dragon breath clouds. Other elemental dragons could also do this, but have other effects besides your usual high-damage AoE cloud.

**Comment by Sunconure11** [comment]
There is an unused breath weapon mechanic, but this codebase is nightmarish to work with. I will probably need to commission someone to clean it up lmao.
